apiVersion: v2
name: cncf-demo-app
description: Sample Helm chart for CNCF Webinar Demo
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mariadb
    version: "0.15.0"
    repository: "oci://ghcr.io/cloudpirates-io/helm-charts"
  - name: memcached
    version: "0.11.0"
    repository: "oci://ghcr.io/cloudpirates-io/helm-charts"
