apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: scan-cncf-demo
  namespace: renovate-operator
spec:
  discoveryFilter: mogenius/cncf-renovate
  extraEnv:
  - name: RENOVATE_PLATFORM
    value: github
  - name: RENOVATE_ENDPOINT
    value: https://api.github.com/
  image: renovate/renovate:43.59.5
  parallelism: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secrets
